### ISSUE TITLE
Framerate drops when getting close to the gaussian model

### ISSUE THREAD

**Issue by getrasa** [ninjamode/Unity-VR-Gaussian-Splatting#5] opened 2024-11-18 13:01 UTC
Hi,

First, I want to thank you for this amazing project. I've encountered a performance issue that I'd like to report.

**Setup:**
Unity Version: 2022.3.51f1
Scene: "Test" scene
Changes Made: Replaced the default gaussian model with my custom model (350k splats) 
Settings: Tested on both High and Medium quality of gaussian splat import

**Issue:**
I'm experiencing significant performance drops when the VR camera gets close to my custom gaussian model. This occurs regardless of whether I use High or Medium quality settings.

**Additional Information:**
- When looking from further away while the entire model is in my view I'm getting an easy 72 fps. The closer I get the worse the framerate gets, sometimes as low as 18fps when my face is almost within the model.
- I'm running it on rtx 4070, CPU is intel i5 8400k
- I played with almost all settings under Gaussian Splat Renderer and nothing seemed to mitigate this issue.

Is this a known issue? How do I resolve it? 

Any help is much appreciated!

**Comment by ninjamode** [comment] 2024-11-18 16:34
I think a RTX 4070 should be able to handle this complexity without many issues. I must admit that i did not so far try looking super close into things, but i did not notice such a breakdown in framerate. So thats not expected.

Two things come to mind:
- Can you share your gaussian model?
- Is this VR related? if you try with the original repo at https://github.com/aras-p/UnityGaussianSplatting and move the camera roughly to the same point, do you experience a similar breakdown of performance? (Keeping in mind that we need to render twice as much for VR)

**Comment by fx-lange** [comment] 2024-11-20 08:46
hey, same issue here but first of all thanks a lot for providing your URP VR fix with this repo. works great and is such a help for our prototypes. much appreciated. 

I noticed the heavy performance hit when getting close to a model as well - but already in your demo scene (without any changes!) when moving a body part close to the view/headset - more or less independent of the quality. 

the issue is the same with our own lightweight models (single layer, only 100k splats). 

tested with quest3 standalone but also noticeable via oculus link (4070ti). haven't profiled it yet nor tested with the original repo by aras but it's on my list.

**Comment by getrasa** [comment] 2024-11-20 12:25
Sure. I’ve uploaded my model here: https://drive.google.com/file/d/10nfCFngpiSQnOdqyaVCU4azD36duYDRG/view?usp=sharing
Feel free to use it for testing, although I believe that any larger model could be used to reproduce this issue or perhaps even smaller ones like fx-lange has mentioned.

I haven't tested it with the original repo yet, but judging by this issue I found on the original implementation, this doesn't seem to be VR-related. It describes the same problem: https://github.com/aras-p/UnityGaussianSplatting/issues/10

**Comment by ninjamode** [comment] 2024-11-25 15:13
Thanks for further looking into this issue. I agree that this is especially problematic in VR, where you might want to get very close. I'm still going to close this issue here and continue in the main GS repository.

I don't have any immediate plans to do something about this issue, but if some good solution comes up i will probably port it here.

**Closed as completed by ninjamode** 2024-11-25 15:13 UTC
